---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm64

steps:
- name: greeting
  image: golang:1.12
  commands:
  - ls
  - go build
  - go test
trigger:
  branch:
  - master
  event:
  - push
